export const CompanyName='Company Name Required'
export const Name='Name should be Required'
export const Category='Category should be Required'
export const middleCategory="Middle Category Should be Required"
export const subCategory="Sub Category Should be Required"
export const price="Price Should be Required"
export const size="Size Should be Required"
export const weight="Weight Should be Required"
export const color="Color Should be Required"
export const mrp="Mrp Should be Required"
export const discount="Discount Should be Required"
