export const BrandActionTypes={
    ADD_BRAND_START:'ADD_BRAND_START',
    ADD_BRAND_SUCCESS:'ADD_BRAND_SUCCESS',
    ADD_BRAND_FAILURE:'ADD_BRAND_FAILURE',
    REMOVE_BRAND:'REMOVE_BRAND',
    UPDATE_BRAND:'UPDATE_BRAND',
    DELETE_BRAND_START:'DELETE_BRAND_START',
    DELETE_BRAND_SUCCESS:'DELETE_BRAND_SUCCESS',
    DELETE_BRAND_FAILURE:'DELETE_BRAND_FAILURE',
    FETCH_BRAND_START:'FETCH_BRAND_START',
    FETCH_BRAND_SUCCESS:'FETCH_BRAND_SUCCESS',
    FETCH_BRAND_FAILURE:'FETCH_BRAND_FAILURE'
};

export default BrandActionTypes;
