export const ProductActionTypes={
    ADD_ITEM_START:'ADD_ITEM_START',
    ADD_ITEM_SUCCESS:'ADD_ITEM_SUCCESS',
    ADD_ITEM_FAILURE:'ADD_ITEM_FAILURE',
    REMOVE_ITEM:'REMOVE_ITEM',
    UPDATE_ITEM:'UPDATE_ITEM',
    DELETE_ITEM_START:'DELETE_ITEM_START',
    DELETE_ITEM_SUCCESS:'DELETE_ITEM_SUCCESS',
    DELETE_ITEM_FAILURE:'DELETE_ITEM_FAILURE',
    FETCH_COLLECTIONS_START:'FETCH_COLLECTIONS_START',
    FETCH_COLLECTIONS_SUCCESS:'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE:'FETCH_COLLECTIONS_FAILURE'
};

export default ProductActionTypes;
